-- MySQL Script generated by MySQL Workbench
-- Sat Nov 18 20:38:47 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `editora` (
  `edtr_id` VARCHAR(10) NOT NULL,
  `edtr_cnpj` VARCHAR(14) NOT NULL,
  `edtr_nome` VARCHAR(50) NULL,
  PRIMARY KEY (`edtr_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livro` (
  `lvr_isbn` VARCHAR(13) NOT NULL,
  `lvr_nome` VARCHAR(80) NOT NULL,
  `lvr_lancamento` DATE NOT NULL,
  `lvr_valor` DECIMAL(6,2) NOT NULL,
  `editora_edtr_id` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`lvr_isbn`),
  INDEX `fk_livro_editora1_idx` (`editora_edtr_id` ASC) VISIBLE,
  CONSTRAINT `fk_livro_editora1`
    FOREIGN KEY (`editora_edtr_id`)
    REFERENCES `editora` (`edtr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autor` (
  `atr_id` VARCHAR(11) NOT NULL,
  `atr_rna` VARCHAR(13) NOT NULL,
  `atr_pnome` VARCHAR(100) NOT NULL,
  `atr_unome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`atr_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `socio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socio` (
  `socio_id` VARCHAR(10) NOT NULL,
  `socio_pnome` VARCHAR(100) NOT NULL,
  `socio_unome` VARCHAR(100) NOT NULL,
  `socio_cpf` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`socio_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `livro_has_autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livro_has_autor` (
  `livro_lvr_isbn` VARCHAR(13) NOT NULL,
  `autor_atr_id` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`livro_lvr_isbn`, `autor_atr_id`),
  INDEX `fk_livro_has_autor_autor1_idx` (`autor_atr_id` ASC) VISIBLE,
  INDEX `fk_livro_has_autor_livro_idx` (`livro_lvr_isbn` ASC) VISIBLE,
  CONSTRAINT `fk_livro_has_autor_livro`
    FOREIGN KEY (`livro_lvr_isbn`)
    REFERENCES `livro` (`lvr_isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livro_has_autor_autor1`
    FOREIGN KEY (`autor_atr_id`)
    REFERENCES `autor` (`atr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `editora_has_autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `editora_has_autor` (
  `editora_edtr_id` VARCHAR(10) NOT NULL,
  `autor_atr_id` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`editora_edtr_id`, `autor_atr_id`),
  INDEX `fk_editora_has_autor_autor1_idx` (`autor_atr_id` ASC) VISIBLE,
  INDEX `fk_editora_has_autor_editora1_idx` (`editora_edtr_id` ASC) VISIBLE,
  CONSTRAINT `fk_editora_has_autor_editora1`
    FOREIGN KEY (`editora_edtr_id`)
    REFERENCES `editora` (`edtr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_editora_has_autor_autor1`
    FOREIGN KEY (`autor_atr_id`)
    REFERENCES `autor` (`atr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exemplares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exemplares` (
  `expl_id` VARCHAR(10) NOT NULL,
  `livro_lvr_isbn` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`expl_id`),
  INDEX `fk_exemplares_livro1_idx` (`livro_lvr_isbn` ASC) VISIBLE,
  CONSTRAINT `fk_exemplares_livro1`
    FOREIGN KEY (`livro_lvr_isbn`)
    REFERENCES `livro` (`lvr_isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprestimo` (
  `socio_socio_id` VARCHAR(10) NOT NULL,
  `exemplares_expl_id` VARCHAR(10) NOT NULL,
  `emprt_data_emprestimo` DATE NOT NULL,
  `emprt_data_devolucao` DATE NOT NULL,
  PRIMARY KEY (`socio_socio_id`, `exemplares_expl_id`),
  INDEX `fk_socio_has_exemplares_exemplares1_idx` (`exemplares_expl_id` ASC) VISIBLE,
  INDEX `fk_socio_has_exemplares_socio1_idx` (`socio_socio_id` ASC) VISIBLE,
  CONSTRAINT `fk_socio_has_exemplares_socio1`
    FOREIGN KEY (`socio_socio_id`)
    REFERENCES `socio` (`socio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_socio_has_exemplares_exemplares1`
    FOREIGN KEY (`exemplares_expl_id`)
    REFERENCES `exemplares` (`expl_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
